Implement Executor
Story-Of-Alicia/alicia-server pull request #32
Opened 2024-12-24 00:51 UTC by martinprejsa

Based upon @dxlpi scheduler.

Executor executes tasks from a queue. If task takes longer than the specified timeout interval. The task is cancelled.

2024-12-24 10:28 UTC, rgnter commented on src/server/Executor.cpp
> +      if (timeout > 0)
Make this an early return instead of nesting.

2024-12-25 19:06 UTC, alborrajo requested changes

2024-12-25 19:06 UTC, alborrajo commented on src/libserver/Executor.cpp
> +      if (pthread_create(&taskThread, nullptr, &task_executor, &param) != 0)
Why are we mixing C++ threads with C pthread?

2024-12-25 19:06 UTC, alborrajo commented on include/libserver/Executor.hpp
> +  Executor(uint64_t const timeout);
It'd be good to specify in the variable name the units we expect the timeout to be in, in this case milliseconds, or have the constructor be supplied with a std::chrono

2024-12-25 19:06 UTC, alborrajo commented on src/libserver/Executor.cpp
> +          exit(0XDEAD);
I doubt we'd want to exit like this

2024-12-25 19:06 UTC, alborrajo commented on src/libserver/Executor.cpp
> +          exit(0XDEAD);
ditto

2024-12-25 19:06 UTC, alborrajo commented on src/libserver/Executor.cpp
> +          exit(0xDEAD);
ditto regarding exit

2024-12-25 19:06 UTC, alborrajo commented on src/libserver/Executor.cpp
> +          // i'm pretty sure free needs to be called, but this throws sigsegv
unless ret happened to point to a malloc'd address, it doesn't have to be called, which in this case it isn't

2024-12-25 19:06 UTC, alborrajo commented on src/libserver/Executor.cpp
> +        //free(&ret);
ditto regarding ret and malloc

2024-12-25 19:06 UTC, alborrajo commented on tests/src/TestExecutorTimeout.cpp
> +  delete executor;
This test has no assertions. It should check something to verify that the executor killed the task due to a timeout, for example, have the task sleep for 500ms and then flip a boolean and have the assertion check that the boolean hasnt been flipped

2025-02-25 13:22 UTC, merged