Create Dockerfile
Story-Of-Alicia/alicia-server pull request #36
Opened 2024-12-30 00:40 UTC by SergeantSerk

Working Dockerfile. Replicates build instructions. Minified base image.

Currently does not use alpine as final image due to compiling issues. Resources are copied over.

2024-12-30 00:53 UTC, rgnter commented on Dockerfile
> +RUN git submodule update --init --recursive
If we're initializing the submodules as a part of the build step, shouldn't we also clone the repository? 
My train of though behind this is that if repository is already provided, it should be already a valid one.

2024-12-30 00:54 UTC, rgnter commented on Dockerfile
> +    cmake --build . --parallel
This should also specify `-DCMAKE_BUILD_TYPE=Release`

2024-12-30 01:01 UTC, rgnter commented on Dockerfile
> +RUN git submodule update --init --recursive
Disregard, I somehow failed to realize that this is within the repository itself.

2024-12-30 15:15 UTC, alborrajo commented on Dockerfile
> +COPY --from=builder ${BUILDER_REPO_PATH}/resources/* .
Don't they already get copied as part of the build process? This shouldn't be necessary

2024-12-31 13:21 UTC, rgnter requested changes

2024-12-31 13:21 UTC, rgnter commented on Dockerfile
> +FROM ubuntu:latest AS builder
Set yourself as the author, and leave the maintainer as is.
```suggestion
# syntax=docker/dockerfile:1
ARG BUILDER_REPO_PATH=/builder/alicia-server

LABEL author="<your_name>" maintainer="dev@storyofalicia.com"

FROM ubuntu:latest AS builder
```

2024-12-31 13:21 UTC, rgnter commented on Dockerfile
> +    cmake --build ${BUILDER_REPO_PATH}/build --parallel
We've already set the workdir, let's use relative paths from now on. 
Also please install the executable in the build step, so that we can copy it later, without copying the unnecessary build objects. 
```suggestion
RUN cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} . -B ./build
RUN cmake --build ./build --parallel
RUN cmake --install ./build --prefix .
```

2024-12-31 13:21 UTC, rgnter commented on Dockerfile
> +WORKDIR /game
Here we will copy the installed server to the new image. 
I've changed the install location to `/opt/alicia-server` instead of the folder within the root. 
```suggestion
WORKDIR /opt/alicia-server
COPY --from=builder ${BUILDER_REPO_PATH}/dist .
```

2024-12-31 13:21 UTC, rgnter commented on Dockerfile
> +ENTRYPOINT ["/server/alicia-server"]
```suggestion
VOLUME [ "/opt/alicia-server" ]
ENTRYPOINT ["/opt/alicia-server/alicia-server"]
```

2024-12-31 13:21 UTC, rgnter commented on Dockerfile
> +    cmake --build ${BUILDER_REPO_PATH}/build --parallel
Please modify the root `CMakeLists.txt` of the project to make installing possible. Add this at the end of the file:

```cmake
install(TARGETS alicia-server DESTINATION dist)
install(DIRECTORY resources DESTINATION dist)
```

2024-12-31 13:23 UTC, rgnter commented
With all of these changes, the image size is around ~79MB. 👍

2024-12-31 13:34 UTC, rgnter commented
Also could the runner maybe be alpine?

2024-12-31 14:07 UTC, SergeantSerk commented
> Also could the runner maybe be alpine?

Been running into musl/glibc issue here. Alpine needs binaries compiled with musl which is why I currently opted for the `ubuntu` base image to keep things simple and running. See this [SO answer](https://stackoverflow.com/a/66974607). Will look into it.

With `alpine:latest` final image:
```bash
$ docker logs -f alicia-server
exec /opt/alicia-server/alicia-server: no such file or directory
```

2025-01-01 14:40 UTC, rgnter commented
> > Also could the runner maybe be alpine?
> 
> Been running into musl/glibc issue here. Alpine needs binaries compiled with musl which is why I currently opted for the `ubuntu` base image to keep things simple and running. See this [SO answer](https://stackoverflow.com/a/66974607). Will look into it.
> 
> With `alpine:latest` final image:
> 
> ```shell
> $ docker logs -f alicia-server
> exec /opt/alicia-server/alicia-server: no such file or directory
> ```

Yep, that's caused because we're not building with musl and it can't find the dynamically linked glibc libraries. Let's keep it on Ubuntu then. 

I'd also ask you to add `--chown alicia` to the COPY command when copying from build stage to runner stage, so we don't have issues with that later on.

2025-01-01 14:44 UTC, rgnter requested changes

2025-01-01 14:44 UTC, rgnter commented on .dockerignore
> +build/
Some more common build directory names
```suggestion
build/
out/
cmake-build-*/
```

2025-01-01 14:44 UTC, rgnter commented on Dockerfile
> +COPY --from=builder ${BUILDER_REPO_PATH}/dist .
```suggestion
COPY --from=builder --chown=alicia ${BUILDER_REPO_PATH}/dist .
```

2025-01-01 14:44 UTC, rgnter commented on Dockerfile
> +RUN cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} . -B ./build
We'll never be running tests in the docker container, we don't have to compile them. 
```suggestion
RUN cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_TESTS=False . -B ./build
```

2025-01-01 14:45 UTC, rgnter commented
Last round of reviews, and we can merge this to the master.

2025-01-01 15:02 UTC, rgnter approved these changes

2025-01-01 15:03 UTC, merged

2025-01-01 15:04 UTC, rgnter commented
@SergeantSerk If you're on discord (https://discord.gg/storyofalicia), feel free to message so I can give you a contributor role if you're intereseted