Creating database for the server using postgre and libpq++
Story-Of-Alicia/alicia-server pull request #6
Opened 2024-11-12 05:44 UTC by dxlpi

I'm not done with creating the database! I just wanted to get checked by you guys to see if I'm on the right track or not. Any suggestions or comments are welcomed

2024-11-12 08:08 UTC, rgnter requested changes

2024-11-12 08:08 UTC, rgnter commented on CMakeLists.txt
> +find_package(PkgConfig REQUIRED)
This will not work on Windows.

2024-11-12 08:08 UTC, rgnter commented on CMakeLists.txt
> +add_subdirectory(3rd-party/spdlog)
This was fine like it was before. 
`3rd-party` folder contains CMakeLists.txt file which points to subdirectories.

2024-11-12 08:08 UTC, rgnter commented on src/.DS_Store
Add to .gitignore

2024-11-12 08:23 UTC, rgnter commented
Instead of using pkg-config, do the following:

1. Clone a submodule of libpqxx:
```
git submodule add https://github.com/jtv/libpqxx.git 3rd-party/libpqxx
```

2. Add the submodule to the CMakeLists of the `3rd-party` folder.
```diff
add_subdirectory(spdlog)
+add_subdirectory(libpqxx)
```

3. Link the target provided by libpqxx with our poject.
```cmake
target_link_libraries(alicia-server
        PRIVATE project-properties alicia-libserver spdlog::spdlog pqxx)
```

2024-11-14 01:00 UTC, dxlpi commented
@rgnter I made the changes accordingly! Please review the changes and lmk if there's anything else I need to fix. Thanks :)

2024-11-14 07:35 UTC, rgnter requested changes

2024-11-14 07:35 UTC, rgnter commented on CMakeLists.txt
> +pkg_check_modules(LIBPQXX REQUIRED libpqxx)
You don't need this anymore. If you do, the build isn't setup correctly.

2024-11-14 07:37 UTC, rgnter commented
For future reference, I recommend rebasing your squashed feature branch instead of merging it with master. This way the commits that don't belong to this MR will not show up.

2024-11-18 23:17 UTC, closed without merging